# Form implementation generated from reading ui file 'Fridge_open.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from Fridge import *
from gui2 import *

class Ui_Dialog(object):
    def open_window2(self):
        '''
        Function opens the second window.
        '''
        self.window = QtWidgets.QMainWindow()
        self.ui2 = Ui_popup()
        self.ui2.setupUi(self.window, fridge_instance)
        self.window.show()
    def setupUi(self, Dialog, fridge: type[Fridge]) -> None:
        '''
        Function creates the main window.
        :param Dialog: Creates the window.
        :param fridge: Calls back to Fridge.
        '''
        self.fridge = fridge
        Dialog.setObjectName("Dialog")
        Dialog.resize(155, 96)
        Dialog.setMinimumSize(QtCore.QSize(155, 96))
        Dialog.setMaximumSize(QtCore.QSize(155, 96))
        self.fridgelabel = QtWidgets.QLabel(parent=Dialog)
        self.fridgelabel.setGeometry(QtCore.QRect(10, 0, 137, 42))
        self.fridgelabel.setObjectName("fridgelabel")
        self.door = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.door.setGeometry(QtCore.QRect(40, 70, 75, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.door.sizePolicy().hasHeightForWidth())
        self.door.setSizePolicy(sizePolicy)
        self.door.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.door.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Close)
        self.door.setObjectName("door")

        self.pushButton = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton.setGeometry(QtCore.QRect(40, 40, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.fridge.open)
        self.pushButton.clicked.connect(self.open_window2)

        self.retranslateUi(Dialog)
        self.door.accepted.connect(Dialog.accept) # type: ignore
        self.door.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog) -> None:
        '''
        Function creates the text for the window.
        :param Dialog: Creates teh text for the window.
        '''
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.fridgelabel.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:26pt; font-weight:600;\">FRIDGE</span></p></body></html>"))
        self.pushButton.setText(_translate("Dialog", "Open"))


import sys
app = QtWidgets.QApplication(sys.argv)
fridge_instance = Fridge()
Dialog = QtWidgets.QDialog()
ui = Ui_Dialog()
ui.setupUi(Dialog, fridge_instance)
Dialog.show()
sys.exit(app.exec())
